### ISSUE TITLE
Can you provide train.json data? Thank you

### ISSUE THREAD

**Issue by chenhuizi** [gswycf/Joint-Extraction-of-Entities-and-Relations-Based-on-a-Novel-Tagging-Scheme#1]
Can you provide train.json data? Thank you

**Comment by BaiStone2017** [comment]
I have this dataset,you can download it from https://pan.baidu.com/s/1CfltNNGxfimiPKEYm-wfIg

**Comment by gswycf** [comment]
link：https://drive.google.com/drive/folders/1WWKkvwtbg5fLmh3CnjPC2luxyHooyvmR?usp=sharing
