### ISSUE TITLE
 What is the data structure of train.json 

### ISSUE THREAD

**Issue by chenhuizi** [gswycf/Joint-Extraction-of-Entities-and-Relations-Based-on-a-Novel-Tagging-Scheme#2]
What is the data structure of train.json

**Comment by gswycf** [comment]
i'm sorry,just little busy recently，i‘m trying upload those file to Google Drive，link：https://drive.google.com/drive/folders/1WWKkvwtbg5fLmh3CnjPC2luxyHooyvmR?usp=sharing

**Comment by sathish331977** [comment]
i could not find train.json here, could you please upload
