### ISSUE TITLE
Fix bad Arxiv link in readme

### ISSUE THREAD

**Issue by impredicative** [gswycf/Joint-Extraction-of-Entities-and-Relations-Based-on-a-Novel-Tagging-Scheme#3]
The link to the paper Joint Extraction of Entities and Relations Based on a Novel Tagging Scheme in the readme is incorrect. It should evidently be https://arxiv.org/abs/1706.05075

**Comment by gswycf** [comment]
thanks, i'm a little busy recently

**Comment by z786760876** [comment]
because my GPU is too old，pytorch don't support it anymore，so i want to ask：
this code can just use CPU run，without GPU？

**Comment by gswycf** [comment]
> because my GPU is too old，pytorch don't support it anymore，so i want to ask：
> this code can just use CPU run，without GPU？

of course，if your cpu is fast enough，but you need change  code in “train。py” a little bit，besides，i already upload data and model to google drive， you can see in readme
